---
address_range_test_ranges:
  - name: Test Address Range 1
    ip_address_first: 192.168.201.1
    ip_address_last: 192.168.201.10
  - name: Test Address Range 2
    ip_address_first: 192.168.202.1
    ip_address_last: 192.168.202.10
  - name: Test Address Range 3
    ip_address_first: 192.168.203.1
    ip_address_last: 192.168.203.10
