$ANSIBLE_VAULT;1.1;AES256
34653630343565353731346431303530343463326633343135663861356435356361303538376330
6566656530303561313162303635373938313939376162330a666132323732643566323832336138
35333932306563383661646464613235376439613135613432663664646138343761323866303733
6430333431303839360a653831303631343936643564653835303137396230646266336531333264
61376231396438393165356237393362396261323862663164366164373933313765383262653233
66363039373263303132313834316136306430306435316565373861613831316264343139373564
636232363338333536353633623265653533
