gaia_build_dns1: "172.31.0.2"
gaia_build_dns2: "8.8.8.8"
gaia_build_dns3: "8.8.4.4"
gaia_build_dns_domain: lasthop.io

gaia_build_static_routes:
  - destination: "172.31.128.0"
    mask: 21
    next_hop: "172.31.128.1"
    interface: "eth1"
