---
- name: Firewall management (ansible)
  check_point.mgmt.cp_mgmt_access_rule:
    layer: "Network"
    name: "Ansible Management Access"
    source:
      - Ansible Server
    destination:
      - "{{ fw_name }}"
    service: Any
    action: "Accept"
    position: 1
  notify:
    - FW Publish
    - Install Policy

- name: SSH Access to FW
  check_point.mgmt.cp_mgmt_access_rule:
    layer: "Network"
    name: "SSH Access"
    source: Any
    destination:
      - "{{ fw_name }}"
    service: SSH
    action: "Accept"
    position: 2
  notify:
    - FW Publish
    - Install Policy
