  1 ---
  2 - name: Firewall management (ansible)
  3   check_point.mgmt.cp_mgmt_access_rule:
  4     layer: "Network"
  5     name: "Ansible Management Access"
  6     source:
  7       - Ansible Server
  8     destination:
  9       - "{{ fw_name }}"
 10     service: Any
 11     action: "Accept"
 12     position: 1
 13   notify:
 14     - FW Publish
 15     - Install Policy
 16 
 17 - name: SSH Access to FW
 18   check_point.mgmt.cp_mgmt_access_rule:
 19     layer: "Network"
 20     name: "SSH Access"
 21     source: Any
 22     destination:
 23       - "{{ fw_name }}"
 24     service: SSH
 25     action: "Accept"
 26     position: 2
 27   notify:
 28     - FW Publish
 29     - Install Policy
