---
- name: Gaia Save Config
  check_point.gaia.cp_gaia_run_script:
    script: clish -c "save config"

- name: FW Publish
  check_point.mgmt.cp_mgmt_publish:

- name: Install Policy
  check_point.mgmt.cp_mgmt_install_policy:
    policy_package: "Standard"
    targets:
      - "{{ fw_name }}"

